name: BossShopPro
version: ${project.version}
api-version: 1.13
description: The BOSS Shop Plugin *PRO VERSION*
author: Black_ixx, ProMCTeam
main: org.black_ixx.bossshop.BossShop
folia-supported: true
softdepend: [ProRPGItems, ItemsAdder, MagicCosmetics, MythicMobs, PlayerShops GUI, ItemShops, ThirdCurrency, GuiShopManager, LimitedUses, TrickyShops, PlayerPoints, Jobs, Gringotts, VotingPlugin, SilkSpawners, PlaceholderAPI]
loadbefore: [ LimitedUses, ItemShops, PlayerShops, ThirdCurrency, GuiShopManager ]
libraries: [ commons-lang:commons-lang:2.6 ]
commands:
  bs:
   description: BossShop command
  bossshop:
   description: BossShop command
  shop:
   description: BossShop command
permissions:
  BossShop.open:
    description: Allows opening shops via command/sign
    default: op
  BossShop.open.sign:
    description: Allows opening shops via sign
    default: op
  BossShop.open.command:
    description: Allows opening shops via command
    default: op
  BossShop.open.other:
    description: Allows opening shops for other players
    default: op
  BossShop.close:
    description: Allows closing inventories of other players
    default: op
  BossShop.reload:
    description: Allows reloading the plugin
    default: op
  BossShop.createSign:
    description: Allows creating BossShopPro signs
    default: op
  BossShop.bypass:
    description: Allows to bypass the click delay
    default: op
  BossShop.read:
    description: Allows reading and generating itemdata of hold items
    default: op
  BossShop.create:
    description: Allows create shops
    default: op