name: ${project.name}
version: ${project.version}
api-version: 1.13
description: A powerful custom shop creator plugin
authors: [ Black_ixx, MageMonkeyStudio ]
main: studio.magemonkey.genesis.Genesis
folia-supported: true
softdepend: [ Divinity, ItemsAdder, MagicCosmetics, MythicMobs, PlayerShops GUI, ItemShops, ThirdCurrency, GuiShopManager, LimitedUses, TrickyShops, Vault, PlayerPoints, Jobs, Gringotts, VotingPlugin, SilkSpawners, PlaceholderAPI ]
loadbefore: [ LimitedUses, ItemShops, PlayerShops, ThirdCurrency, GuiShopManager ]
libraries: [ org.apache.commons:commons-lang3:${apache.version} ]
commands:
  gen:
    description: Genesis command
  genesis:
    description: Genesis command
  shop:
    description: Genesis command
    aliases: [bs,bossshop]
permissions:
  Genesis.open:
    description: Allows opening shops via command/sign
    default: op
  Genesis.open.sign:
    description: Allows opening shops via sign
    default: op
  Genesis.open.command:
    description: Allows opening shops via command
    default: op
  Genesis.open.other:
    description: Allows opening shops for other players
    default: op
  Genesis.close:
    description: Allows closing inventories of other players
    default: op
  Genesis.reload:
    description: Allows reloading the plugin
    default: op
  Genesis.createSign:
    description: Allows creating Genesis signs
    default: op
  Genesis.bypass:
    description: Allows to bypass the click delay
    default: op
  Genesis.read:
    description: Allows reading and generating itemdata of hold items
    default: op
  Genesis.create:
    description: Allows create shops
    default: op
